services:
  jacht-ros-server:
    image: ghcr.io/tinlas03-2025-vt/server:latest
    container_name: jacht-ros-server
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=42
    ports:
      - "10000:10000/tcp"
